redirectsOrigin = "config"
plugins = []
headers = []

[functions]

[functions.email-sequence-scheduler]
schedule = "0 9 * * *"

[functions."*"]

[build]
publish = "/home/wolfy/Projects/2025/Hub_App_Shop_Integ/public"
publishOrigin = "config"

[build.environment]
NODE_ENV = "production"

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]

[[redirects]]
from = "/apps/finderr/beta"
to = "https://marketing.untrapd.com/apps/finderr/beta/"
status = 301.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/apps/finderr/beta/"
to = "https://marketing.untrapd.com/apps/finderr/beta/"
status = 301.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/"
to = "/index.html"
status = 200.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/templates"
to = "/templates.html"
status = 200.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/dashboard"
to = "/dashboard/index.html"
status = 200.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]